### ISSUE TITLE
UndefinedConversionError

### ISSUE THREAD

**Issue by pdelanauze** [quirkey/soca#33]
Ruby 1.9.3-p194 installed with rvm, fresh install

Latest soca gem installed with the following dependencies, in its own gem set:

```
Successfully installed json-1.4.6
Successfully installed mime-types-1.18
Successfully installed typhoeus-0.2.4
Successfully installed thor-0.14.6
Successfully installed rubyzip-0.9.7
Successfully installed archive-tar-minitar-0.5.2
Successfully installed downlow-0.1.4
Successfully installed fssm-0.2.9
Successfully installed yajl-ruby-1.1.0
Successfully installed version_sorter-1.1.0
Successfully installed jim-0.3.2
Successfully installed sass-3.1.16
Successfully installed chunky_png-1.2.5
Successfully installed compass-0.12.1
Successfully installed mustache-0.99.4
Successfully installed coffee-script-source-1.3.1
Successfully installed multi_json-1.3.2
Successfully installed execjs-1.3.0
Successfully installed coffee-script-2.2.0
Successfully installed soca-0.3.2
```

Cannot get around this error: 

```
/Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/json-1.4.6/lib/json/common.rb:210:in `encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/json-1.4.6/lib/json/common.rb:210:in `generate'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/json-1.4.6/lib/json/common.rb:210:in `generate'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/soca-0.3.2/lib/soca/pusher.rb:88:in `push!'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/soca-0.3.2/lib/soca/cli.rb:111:in `push'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/gems/soca-0.3.2/bin/soca:5:in `<top (required)>'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/bin/soca:19:in `load'
    from /Users/pat/.rvm/gems/ruby-1.9.3-p194@soca/bin/soca:19:in `<main>'
```

**Comment by quirkey** [comment]
What are you running when you get this error? What kind of docs are you trying to push? It looks like its trying to convert a binary file to JSON which would happen if youre uploading bin files not as _attachments.

**Comment by pdelanauze** [comment]
Heh, sorry bout that, been banging my head on this one since yesterday afternoon and skimped out on the details due to a little frustration

Happens when pushing (soca push) on a couch app which used to work with 1.9.3-p0. Was actually able to push it this morning on another mac, since upgrading to 1.9.3-p194 it no longer works

Will check if binary files could be the culprit, also going to try with 1.8x

**Comment by pdelanauze** [comment]
Well.. ree-1.8.7-2012.02 works, gonna stick with that for now
checked the binary attachments and none of them are inline in the design document..
